### ISSUE TITLE
Create a litmus Cypress Image of lighter weight that can be used in the CI at every places

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus-e2e#239]
## Details:

- Today the `.gitlab-ci.yml` of litmus-portal branch contains the cypress image which is not cypress official or litmuschaos image. We need to use litmuschaos image in the code. You can make use of [test-tools](https://github.com/litmuschaos/test-tools) repo for creating litmuschaos image of this [Dockerfile](https://github.com/litmuschaos/litmus-e2e/blob/litmus-portal/build/Dockerfile.Cypress) if this image is fixed and you won't need to change it frequently. Otherwise, you can give this image from GitLab env as well like [this](https://github.com/litmuschaos/litmus-e2e/blob/7072a44c8ec2bbf9c3c6b7523bbacb17a566efb8/.gitlab-ci.yml#L16).

_Originally posted by @uditgaurav in https://github.com/litmuschaos/litmus-e2e/pull/237#discussion_r583192193_

**Comment by Jonsy13** [comment]
Closing this issue as it is fixed in #242 ( Image taken as env from Gitlab variables )
