### ISSUE TITLE
(Litmus-Chore): Add a BDD to test Node Label functionality for selecting target node in node level experiment

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus-e2e#260]
## Details

from https://github.com/litmuschaos/litmus-go/pull/345 we have added:

- _Ability to filter target node by node-label, which can be provided as env._

- _It will first select the target node by TARGET_NODE ENV. If the TARGET_NODE env is not provided then it will select the target node based on the NODE_LABEL ENV. If none of them is provided then it will select the node on which AUT is running._

We need to add an e2e test case for the same!!!

**Comment by neelanjan00** [comment]
Starting the development of E2E test cases for the above use case.

**Comment by uditgaurav** [comment]
The test is successfully added and running in the pipeline (https://github.com/litmuschaos/litmus-e2e/pull/290). Thanks @neelanjan00 !
