### ISSUE TITLE
Broken links in Auth, Teaming and User-Management Tests

### ISSUE THREAD

**Issue by Aman-Codes** [litmuschaos/litmus-e2e#296]
All the links under the heading **Auth, Teaming and User-Management Tests** are broken on https://litmuschaos.github.io/litmus-e2e/portal-pipeline/portal.

![image](https://user-images.githubusercontent.com/54680709/129550059-999358cf-d1b4-42d2-bf20-e383163f3580.png)

## Broken links reason:
- Missing `testcases` folder in `gh-pages` branch.

## Possible Fix:
- Update links to point to  files in `litmus-portal` branch.
- Copy `testcases` folder from `litmus-portal` to `gh-pages` branch.

**Comment by uditgaurav** [comment]
cc: @Jonsy13

**Comment by Aman-Codes** [comment]
Closed by #301

**Comment by Jonsy13** [comment]
@Aman-Codes I'm raising one more PR just now, as links correction got missed, That will fix it.
