### ISSUE TITLE
Refactor workflows scheduling e2e tests

### ISSUE THREAD

**Issue by Jonsy13** [litmuschaos/litmus-e2e#315]
**This issue will be used for tracking Refactoring of e2e tests for workflows scheduling through ChaosCenter**
> Follows this issue https://github.com/litmuschaos/litmus/issues/3114

- [x] Test case to verify the accessibility of create-workflow page.
- [x] Test case to schedule a predefined workflow (First time user experience).
- [x] Test case to schedule a workflow from chaoshub & tune the workflow configuration with non-existing target-application. (Negative Case)
- [x] Test case to schedule a workflow from chaoshub & tune the workflow configuration with an existing target-application. (Positive case)
- [x] Test case to schedule a workflow by uploading a workflow manifest. (Positive case)
- [x] Test case to schedule a workflow by uploading a wrong manifest or incorrect experiment or engine configurations. (Negative case)
- [x] Test case to schedule a workflow on a recurring basis.

**For more information about above tests, Refer -**  [Workflows Scheduling Testsuite doc](https://github.com/litmuschaos/litmus-e2e/blob/website/portal-pipeline/TCID-EC2-Portal-GUI-Workflow-SchedulingOps.md)

**We would like to have generic functions for workflow scheduling validation on k8s on Cluster** 

- [x] Validation of workflow/ cron-workflow creation on cluster after scheduling
- [x] Validation of workflow final status on the cluster.

**Workflow CRUD Operations**
- [x] Rerunning a non-recurring schedule
- [x] Disabling a recurring schedule
- [x] Deleting a schedule
- [x] Downloading the workflow manifest from the schedules table.

**Comment by DhananjayPurohit** [comment]
Here's the PRs for above tests:-
https://github.com/litmuschaos/litmus-e2e/pull/305
https://github.com/litmuschaos/litmus-e2e/pull/334
https://github.com/litmuschaos/litmus-e2e/pull/335

**Comment by Jonsy13** [comment]
Thanks @DhananjayPurohit Great Work!
