### ISSUE TITLE
Add e2e tests for workflow statistics

### ISSUE THREAD

**Issue by Jonsy13** [litmuschaos/litmus-e2e#316]
**This issue will be used to track the e2e tests for workflow statistics**
> Follows issue https://github.com/litmuschaos/litmus/issues/3114

- [x] Test case to verify the accessibility of workflow statistics Tab.
- [x] Test case to schedule a Custom Chaos workflow (Non-Recurring) & verify the workflow statistics data [positive case --> Existing target App]
- [x] Test case to schedule a Custom Chaos workflow (Non-Recurring) & verify the workflow statistics data [negative case --> Non-Existing target App]
- [x] Test case to schedule a Custom Chaos workflow (Recurring) & verify the workflow statistics data [positive case --> Existing target App]
- [x] Rerun a non-recurring workflow & verify the statistics.
- [x] Test case to verify the details in the workflow statistics tab.

**For more information about above tests, Refer -** [ Workflows Statistics Testsuite Doc](https://github.com/litmuschaos/litmus-e2e/blob/website/portal-pipeline/TCID-EC2-Portal-GUI-WorkflowStatistics.md)

**Comment by DhananjayPurohit** [comment]
Here's the PR for the above tests:-
https://github.com/litmuschaos/litmus-e2e/pull/330
