### ISSUE TITLE
Add E2E tests for Datasource & Dashboards configuration

### ISSUE THREAD

**Issue by Jonsy13** [litmuschaos/litmus-e2e#348]
This issue will be used to track the e2e tests for Datasources & Dashboards configuration & validation

> Follows issue litmuschaos/litmus#3114

### Datasources

- [x] Test case to validate the configuration of datasources with wrong details (Negative case).
- [x] Test case to validate the configuration of datasources with correct details (correct endpoint of datasource) 
  - Datasource should be added to datasource table.
   - All datasource details should be validated from datasource table
- [x] Testcase to configure existing datasource with incorrect endpoint (Negative case)
- [x] Testcase to configure existing datasource with correct details (Positive case )
    - Change name of datasource & validate the same in table after configuring.
- [x] Testcase to delete existing datasource & validate the same in table. 

### Dashboards 

- [x] Test case to add a dashboard & validate the dashboard details on dashboard screen & dashboards table
- [x] Test case to configure the dashboard with correct details (Name can be edited & checked in table again)
- [x] Test case to delete the existing dashboard.

**Comment by DhananjayPurohit** [comment]
I have made PRs after covering all the above tests:-
https://github.com/litmuschaos/litmus-e2e/pull/343
https://github.com/litmuschaos/litmus-e2e/pull/358
